export const CFG = {
  WIDTH: 800,
  HEIGHT: 480,
  SCALE: 2,
  FIELD_WORLD_W: 3000,
  FIELD_WORLD_H: 480,

  YARD_PX: 22,
  HASH_OFFSET: 100,
  FIELD_Y_TOP: 60,
  FIELD_Y_BOT: 420,
  FIELD_CENTER_Y: 240,

  QUARTER_SECONDS: 120,
  PLAY_CLOCK: 30,

  TILE: 8,
  PLAYER_W: 12,
  PLAYER_H: 18,
  BALL_W: 8,
  BALL_H: 5,

  COLORS: {
    SKY: 0x1a1a2e,
    FIELD: 0x2d5a27,
    FIELD_ALT: 0x265223,
    LINE: 0xffffff,
    ENDZONE_A: 0x1a3a8a,
    ENDZONE_B: 0x8b0000,
    HASH: 0xcccccc,
    BALL: 0x8b4513,
    BALL_STRIPE: 0xffffff,
    UI_BG: 0x0a0a0a,
    UI_PANEL: 0x1e1e2e,
    GOLD: 0xffd700,
    CYAN: 0x00ffff,
    GREEN_HI: 0x00ff88,
    RED_HI: 0xff4444,
    GRAY: 0x888888,
  },

  TEAM_A: {
    name: 'Ironclad FC',
    city: 'IRON CITY',
    abbr: 'IFC',
    primary: 0x1a3a8a,
    secondary: 0xffd700,
    textColor: '#ffd700',
  },
  TEAM_B: {
    name: 'Red Storm',
    city: 'STORM BAY',
    abbr: 'STM',
    primary: 0x8b0000,
    secondary: 0xc8c8c8,
    textColor: '#c8c8c8',
  },

  POSITIONS: {
    QB:  { label: 'QB',  name: 'Quarterback',       side: 'OFF', slots: 3 },
    RB:  { label: 'RB',  name: 'Running Back',       side: 'OFF', slots: 4 },
    FB:  { label: 'FB',  name: 'Fullback',           side: 'OFF', slots: 1 },
    WR:  { label: 'WR',  name: 'Wide Receiver',      side: 'OFF', slots: 6 },
    TE:  { label: 'TE',  name: 'Tight End',          side: 'OFF', slots: 3 },
    LT:  { label: 'LT',  name: 'Left Tackle',        side: 'OFF', slots: 2 },
    LG:  { label: 'LG',  name: 'Left Guard',         side: 'OFF', slots: 2 },
    C:   { label: 'C',   name: 'Center',             side: 'OFF', slots: 2 },
    RG:  { label: 'RG',  name: 'Right Guard',        side: 'OFF', slots: 2 },
    RT:  { label: 'RT',  name: 'Right Tackle',       side: 'OFF', slots: 2 },
    DE:  { label: 'DE',  name: 'Defensive End',      side: 'DEF', slots: 4 },
    DT:  { label: 'DT',  name: 'Defensive Tackle',   side: 'DEF', slots: 3 },
    MLB: { label: 'MLB', name: 'Middle Linebacker',  side: 'DEF', slots: 2 },
    OLB: { label: 'OLB', name: 'Outside Linebacker', side: 'DEF', slots: 4 },
    CB:  { label: 'CB',  name: 'Cornerback',         side: 'DEF', slots: 6 },
    FS:  { label: 'FS',  name: 'Free Safety',        side: 'DEF', slots: 2 },
    SS:  { label: 'SS',  name: 'Strong Safety',      side: 'DEF', slots: 2 },
    K:   { label: 'K',   name: 'Kicker',             side: 'ST',  slots: 1 },
    P:   { label: 'P',   name: 'Punter',             side: 'ST',  slots: 1 },
  },

  STAT_LABELS: {
    spd: 'Speed',
    str: 'Strength',
    awr: 'Awareness',
    agi: 'Agility',
    stm: 'Stamina',
    thr: 'Throw Power',
    acc: 'Accuracy',
    ctc: 'Catching',
    rtr: 'Route Run',
    blk: 'Blocking',
    tck: 'Tackling',
    cvr: 'Coverage',
    kpw: 'Kick Power',
    kac: 'Kick Acc',
  },

  OFFENSE_PLAYS: [
    { id: 'iz', name: 'Inside Zone',    type: 'RUN',  desc: 'RB hits the gap inside',      icon: 'run' },
    { id: 'oz', name: 'Outside Zone',   type: 'RUN',  desc: 'RB sweeps outside',           icon: 'run' },
    { id: 'pw', name: 'Power',          type: 'RUN',  desc: 'FB leads through the hole',   icon: 'run' },
    { id: 'ct', name: 'Counter',        type: 'RUN',  desc: 'Delayed cut opposite side',   icon: 'run' },
    { id: 'qk', name: 'QB Sneak',       type: 'RUN',  desc: 'QB sneaks behind center',     icon: 'run' },
    { id: 'sl', name: 'Slant',          type: 'PASS', desc: 'WR cuts inside on slant',     icon: 'pass' },
    { id: 'cu', name: 'Curl',           type: 'PASS', desc: 'WR curls back to QB',         icon: 'pass' },
    { id: 'ps', name: 'Post',           type: 'PASS', desc: 'Deep post route downfield',   icon: 'pass' },
    { id: 'cr', name: 'Cross',          type: 'PASS', desc: 'WR crosses the middle',       icon: 'pass' },
    { id: 'sc', name: 'Screen',         type: 'PASS', desc: 'RB screen behind blockers',   icon: 'pass' },
    { id: 'pa', name: 'Play Action',    type: 'PASS', desc: 'Fake handoff, then pass',     icon: 'pass' },
    { id: 'fl', name: 'Fly Route',      type: 'PASS', desc: 'WR sprints deep downfield',   icon: 'pass' },
    { id: 'fg', name: 'Field Goal',     type: 'KICK', desc: 'Attempt a field goal',        icon: 'kick' },
    { id: 'pu', name: 'Punt',           type: 'KICK', desc: 'Punt the ball downfield',     icon: 'kick' },
  ],

  DEFENSE_PLAYS: [
    { id: 'c1', name: 'Cover 1',   type: 'COVERAGE', desc: 'Man coverage, 1 deep safety'  },
    { id: 'c2', name: 'Cover 2',   type: 'COVERAGE', desc: 'Zone, 2 deep safeties'        },
    { id: 'c3', name: 'Cover 3',   type: 'COVERAGE', desc: 'Zone, 3 deep defenders'       },
    { id: 'c4', name: 'Cover 4',   type: 'COVERAGE', desc: 'Prevent - 4 deep safeties'    },
    { id: 'bl', name: 'MLB Blitz', type: 'BLITZ',    desc: 'MLB rushes the passer'        },
    { id: 'db', name: 'DB Blitz',  type: 'BLITZ',    desc: 'Corner or Safety blitzes'     },
    { id: 'gl', name: 'Goal Line', type: 'FRONT',    desc: '6 linemen at the goal line'   },
    { id: 'nk', name: 'Nickel',    type: 'FRONT',    desc: '5 DBs vs passing formations'  },
  ],
};
